name = "MeanFieldSolver"
uuid = "38f3bb3c-2189-4a32-b5c5-5a34a7f167e0"
authors = ["Yue Zhengyuan <yuezy1997@icloud.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
LinearAlgebra = "1.11.0"
Optim = "1.12.0"
Parameters = "0.12.3"
Printf = "1.11.0"
